# Generated by Django 3.1.5 on 2021-01-24 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210124_1532'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='id_index',
        ),
    ]
