# Generated by Django 3.1.5 on 2021-01-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210124_1534'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['id'], name='id_index'),
        ),
    ]
